# Generated by Django 5.1.4 on 2024-12-08 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Counsellor', 'Counsellor'), ('HOD', 'HOD'), ('Year Incharge', 'Year Incharge')], max_length=20)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('department', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('year', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=5)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('leave_taken', models.IntegerField(default=0)),
                ('balance_leave', models.IntegerField(default=6)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('Casual', 'Casual'), ('Medical', 'Medical'), ('Privilege', 'Privilege')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('proof', models.FileField(blank=True, null=True, upload_to='proofs/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.student')),
            ],
        ),
    ]
