# Generated by Django 3.2.20 on 2024-12-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_counsellor_hod_leaverequest_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
