# Generated by Django 3.2.20 on 2024-12-14 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_student_counsellor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='status',
        ),
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved_by_counsellor', 'Approved by Counsellor'), ('rejected_by_counsellor', 'Rejected by Counsellor'), ('approved_by_hod', 'Approved by HOD'), ('rejected_by_hod', 'Rejected by HOD'), ('final_approved', 'Final Approved'), ('final_rejected', 'Final Rejected')], default='pending', max_length=25)),
                ('counsellor_comment', models.TextField(blank=True, null=True)),
                ('hod_comment', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now=True)),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='lms.leaverequest')),
            ],
        ),
    ]
