# Generated by Django 5.1.4 on 2024-12-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_semester_student_current_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='department',
        ),
    ]
