# Generated by Django 3.2.20 on 2025-01-06 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_remove_semester_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestatus',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.student'),
        ),
    ]
