# Generated by Django 3.2.20 on 2025-01-07 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_leavestatus_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.semester'),
        ),
    ]
