# Generated by Django 5.1.6 on 2025-02-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_leaverequest_hod_id_leaverequest_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaverequest',
            old_name='hod_id',
            new_name='hod',
        ),
    ]
